### ISSUE TITLE
[solr] Incomplete list of zookeeper hosts (ZK_HOST)

### ISSUE THREAD

**Issue by tom-schoener** [PreferredAI/helm-charts#21]
**Affected chart**
preferred-ai/solr:3.0.2

**Describe the bug**

The ZK_HOST solr environment variable is set to:

https://github.com/PreferredAI/helm-charts/blob/932914893918bbb90e0de249f7356a98cc0abd91/charts/solr/templates/statefulset.yaml#L141-L142

This effectively inserts the zookeeper service two times under the same url. Is there a reason for this implementation? The Solr dashboard prompts a ZK status error. I currently work around this by overwriting extraEnvVars to manually set the value to a project specific one, as described in "expected behavior".

It's somewhat similar to this issue: **https://github.com/apache/lucene-solr-operator/issues/171**

**To Reproduce**
Deploy the chart. 

**Expected behavior**
 
```yaml
  - name: ZK_HOST
    value: solr-zookeeper-0.solr-zookeeper-headless.<NAMESPACE>.svc.cluster.local:2181,solr-zookeeper-1.solr-zookeeper-headless.<NAMESPACE>.svc.cluster.local:2181,...
```
Using these Zookeeper hosts, the solr dashboard also displays a green ZK status, meaning that the zk connection string looks good. Of course, this should be dynamic and based on `zookeeper.relicaCount` and the corresponding zookeeper service names. 

**Helm and Kubernetes**:
- Output of `helm version`:
```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}

```
- Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.14-gke.1600", GitCommit:"7c407f5cc8632f9af5a2657f220963aa7f1c46e7", GitTreeState:"clean", BuildDate:"2020-12-07T09:22:27Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by lwj5** [comment]
Hi @tom-schoener, thanks for using the chart.

> This effectively inserts the zookeeper service two times under the same url. Is there a reason for this implementation?

Yes, there's a reason for this. If the connected ZK loses connection, it will switch to the next URL in a round-robin fashion. So, If only one address is specified, then it will take longer for it to re-resolve to another ZK. Specifically, in this case, when we have two URLs pointing to headless, then the switching of the URL will resolve to different instances of ZK no matter how many replicas you have.

Please refer to https://lucene.472066.n3.nabble.com/How-to-resolve-a-single-domain-name-to-multiple-zookeeper-IP-in-Solr-tp4450236p4450301.html for more information.

> The Solr dashboard prompts a ZK status error. I currently work around this by overwriting extraEnvVars to manually set the value to a project specific one, as described in "expected behavior".
> Using these Zookeeper hosts, the solr dashboard also displays a green ZK status, meaning that the zk connection string looks good. Of course, this should be dynamic and based on zookeeper.relicaCount and the corresponding zookeeper service names.

You may do this, however, this would prevent you from scaling ZK automatically using HPA or other means. The "ZK status error" you mention falls under the **Known Issues** section in https://github.com/PreferredAI/helm-charts/tree/master/charts/solr#to-200, and do note that the issue is cosmetic. The bug tracking link to the Solr issue is also available in the section mentioned above.

Essentially, having zookeeper-headless twice fulfills the role that you metioned.

Let me know if you have any more questions, if not I'll proceed to close the issue.

**Comment by tom-schoener** [comment]
Hi @lwj5 
Thanks for the fast response, your explanation is very helpful. It answers my question and I'll remove the "workaround" in our project. I'll close this issue.
